### PR TITLE
Modify model 

### PR DESCRIPTION
**Pull request by mirandadrummond**
Adding ipynb of our KNN and cosine similarity model.

### CODE REVIEW

**Review by felixggj — CHANGES_REQUESTED** [review]
Great. Only thing is to remove cosine_similarity.ipynb as we already have one

**Comment by KTsula** [comment]
I agree with Felix, it's better to use the cosine_similarity_model.py and just tweak the function so that it takes as an argument (by default set to false) if it should return similarity or dissimilarity. (basically that would only change how you sort the recommendations, ascending or descending).

**Comment by felixggj** [comment]
Thanks! Also saw there is an error in the file ´knn.ipynb´, seems to be an issue with retrieving the data from Google Drive. ideally we should have all cells executed for the professor to see the outputs.

**Review by felixggj — CHANGES_REQUESTED** [review]
Error in knn.py for loading the data , re-run to see outputs and the rest look good!

**Pull request closed without merging**
