### PR TITLE
update

### PR DESCRIPTION
**Pull request by maudhelen**
removed unecessary dependencies and libraries

### CODE REVIEW

**Review by gabrieldeolaguibel — CHANGES_REQUESTED** [review]
Some requirements are missing versions

**Comment by felixggj** [comment]
We need the following:

streamlit==1.32.2

**Comment by maudhelen** [comment]
> Some requirements are missing versions

category
lightgmb
and sentence

have no version n the current reqs file in main

**Comment by felixggj** [comment]
leave as it is for now.

**Comment by gabrieldeolaguibel** [comment]
> > Some requirements are missing versions
> 
> category lightgmb and sentence
> 
> have no version n the current reqs file in main

We need to find those versions and add them

**Comment by felixggj** [comment]
@KTsula could you add the versions?

**Review by gabrieldeolaguibel — APPROVED** [review]
Better thanks

**Pull request merged**
